#!/bin/bash
if [ -L "$0" ] && [ -x $(which readlink) ]; then
  THIS_FILE="$(readlink -mn "$0")"
else
  THIS_FILE="$0"
fi

CP_BASE="$(dirname "$THIS_FILE")"
java -cp "$CP_BASE/my-toolbox-1.0-SNAPSHOT.jar" fr.turri.Base64Encoder $@
