#!/bin/sh

PLUGININFO_FILE=plugin.info.txt
CURRENT_DATE=$(date +%F)

# Dokuwiki plugin repos have an info file at the root
# The date in this file should match the commit date
# See https://www.dokuwiki.org/devel:badextensions for more infos
if [ -e $PLUGININFO_FILE ]; then
  WRITTEN_DATE=$(grep date $PLUGININFO_FILE | sed 's/date\s\+//')
  if [ x$CURRENT_DATE != x$WRITTEN_DATE ]; then
    echo "Error: current date ($CURRENT_DATE) doesn't match $WRITTEN_DATE (see $PLUGININFO_FILE)"
    exit 1
  fi
fi
